[helpers]

[zsh]
depends = []

[zsh.files]
"zsh/alias.zsh" = "~/.config/zsh/alias.zsh"
"zsh/environment_variables.zsh"="~/.config/zsh/environment_variables.zsh"
"zsh/config_terminal.zsh" = "~/.config/zsh/config_terminal.zsh"
"zsh/terminal/prompt.zsh" = "~/.config/zsh/terminal/prompt.zsh"
zshrc="~/.zshrc"

[zsh.variables]
"aliasFile"="${HOME}/.config/zsh/alias.zsh"
"environmentVariablesFile"="${HOME}/.config/zsh/environment_variables.zsh"
"terminalFile"="${HOME}/.config/zsh/config_terminal.zsh"

[nvim]
depends = ["zsh"]

[nvim.files]
"nvim/init.lua"="${HOME}/.config/nvim/init.lua"
"nvim/lua/settings/remap.lua"="${HOME}/.config/nvim/lua/settings/remap.lua"
"nvim/lua/settings/lazy.lua"="${HOME}/.config/nvim/lua/settings/lazy.lua"
"nvim/lua/settings/basic.lua"="${HOME}/.config/nvim/lua/settings/basic.lua"


"nvim/lua/plugins/telescope.lua"="${HOME}/.config/nvim/lua/plugins/telescope.lua"

[git]
depends = ["zsh"]

[git.files]
"gitconfig" = "~/.gitconfig"

[githook]
depends = [ "zsh"]

[githook.files]
"git/hook/commit-msg"="${HOME}/.config/git/hook/commit-msg"

[tmux]
depends = ["zsh"]

[tmux.files]
"tmux.conf" = "~/.tmux.conf"
