[helpers]

[zsh]
depends = []

[zsh.files]
"zsh/alias.zsh" = "~/.config/zsh/alias.zsh"
"zsh/environment_variables.zsh"="~/.config/zsh/environment_variables.zsh"
"zsh/terminal.zsh" = "~/.config/zsh/terminal.zsh"
zshrc="~/.zshrc"

[zsh.variables]
"aliasFile"="~/.config/zsh/alias.zsh"
"environmentVariablesFile"="~/.config/zsh/environment_variables.zsh"
"terminalFile"="~/.config/zsh/terminal.zsh"

[nvim]
depends = ["zsh"]

[nvim.files]
"nvim/settings/basic_settings.lua" = "~/.config/nvim/lua/settings/basic_settings.lua"
"nvim/settings/lazy.lua" = "~/.config/nvim/lua/settings/lazy.lua"
"nvim/plugins/colorscheme.lua" = "~/.config/nvim/lua/plugins/colorscheme.lua"
"nvim/init.lua" = "~/.config/nvim/init.lua"

[git]
depends = ["zsh"]

[git.files]
"gitconfig" = "~/.gitconfig"
