[helpers]

[zsh]
depends = []

[zsh.files]
"zsh/alias.zsh" = "~/.config/zsh/alias.zsh"
"zsh/environment_variables.zsh"="~/.config/zsh/environment_variables.zsh"
"zsh/config_terminal.zsh" = "~/.config/zsh/config_terminal.zsh"
"zsh/terminal/prompt.zsh" = "~/.config/zsh/terminal/prompt.zsh"
zshrc="~/.zshrc"

[zsh.variables]
"aliasFile"="${HOME}/.config/zsh/alias.zsh"
"environmentVariablesFile"="${HOME}/.config/zsh/environment_variables.zsh"
"terminalFile"="${HOME}/.config/zsh/config_terminal.zsh"

[nvim]
depends = ["zsh"]

[nvim.files]

[git]
depends = ["zsh"]

[git.files]
"gitconfig" = "~/.gitconfig"

[tmux]
depends = ["zsh"]

[tmux.files]
"tmux.conf" = "~/.tmux.conf"
