[helpers]

[zsh]
depends = []

[zsh.files]
"zsh/alias.zsh" = "~/.config/zsh/alias.zsh"
"zsh/environment_variables.zsh"="~/.config/zsh/environment_variables.zsh"
"zsh/config_terminal.zsh" = "~/.config/zsh/config_terminal.zsh"
"zsh/terminal/prompt.zsh" = "~/.config/zsh/terminal/prompt.zsh"
zshrc="~/.zshrc"

[zsh.variables]
"aliasFile"="${HOME}/.config/zsh/alias.zsh"
"environmentVariablesFile"="${HOME}/.config/zsh/environment_variables.zsh"
"terminalFile"="${HOME}/.config/zsh/config_terminal.zsh"

[nvim]
depends = ["zsh"]

[nvim.files]
"nvim/settings/basic_settings.lua" = "~/.config/nvim/lua/settings/basic_settings.lua"
"nvim/settings/lazy.lua" = "~/.config/nvim/lua/settings/lazy.lua"
"nvim/settings/remap.lua" = "~/.config/nvim/lua/settings/remap.lua"

"nvim/plugins/colorscheme.lua" = "~/.config/nvim/lua/plugins/colorscheme.lua"
"nvim/plugins/barbar.lua" = "~/.config/nvim/lua/plugins/barbar.lua"
"nvim/plugins/indent-blankline.lua" = "~/.config/nvim/lua/plugins/indent-blankline.lua"
"nvim/plugins/nvim-tree.lua" = "~/.config/nvim/lua/plugins/nvim-tree.lua"
"nvim/plugins/telescope.lua" = "~/.config/nvim/lua/plugins/telescope.lua"
"nvim/plugins/lsp-server.lua" = "~/.config/nvim/lua/plugins/lsp-server.lua"
"nvim/plugins/lsp-config.lua" = "~/.config/nvim/lua/plugins/lsp-config.lua"
"nvim/plugins/feline.lua" = "~/.config/nvim/lua/plugins/feline.lua" 

"nvim/init.lua" = "~/.config/nvim/init.lua"

[git]
depends = ["zsh"]

[git.files]
"gitconfig" = "~/.gitconfig"
