
[zsh]
depends = []

[zsh.files]
"zsh/alias.zsh"= { target="~/.config/zsh/alias.zsh" , type="template", append="""

#Docker alias
alias dk="docker"
alias dkc="docker-compose"

# Rasbpi
alias rasbpi="ssh ajsobrino@192.168.1.254"

# Vault AWS
alias dtc="aws-vault exec digitaltrust-preprod --"
"""}
