
[zsh]
depends = []

[zsh.files]
"zsh/alias.zsh"= { target="~/.config/zsh/alias.zsh" , type="template", append="""

#Docker alias
alias dk="docker"
alias dkc="docker compose"
"""}

[zsh.variables]
"ZSH_syntax_highlighting"="/home/ajsobrino/softwareDevelopment/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
